#!/bin/sh                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                         
# initialzed asterisk env                                                                                                                                                                                                                                                                
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ysdisk/ysapps/pbxcenter/lib/                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                         
# sleep 120                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                         
# periodic print trunk cc                                                                                                                                                                                                                                                                
while true; do                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
        # count cc                                                                                                                                                                                                                                                                       
        REG=`asterisk -rx "pjsip show cstates" | grep "exten-" | grep "ms," | wc -l`                                                                                                                                                                                   
        echo "$REG extension(s) are registered"                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                         
        WebLogged=`asterisk -rx "pjsip show cstates" | grep "exten-" | grep "transport=WS" | wc -l`                                                                                                                                                                                
        echo "$WebLogged user(s) logged by Linkus Web Client"
		
		MobileLogged=`asterisk -rx "pjsip show cstates" | grep "exten-" | grep "linkus" | wc -l`                                                                                                                                                                                
        echo "$MobileLogged user(s) logged by Linkus Mobile"

		PcLogged=`asterisk -rx "pjsip show cstates" | grep "exten-" | grep "linkuc" | wc -l`                                                                                                                                                                                
        echo "$PcLogged user(s) logged by Linkus PC"
                                                                                                                                                                                                                                                                                  
        # get date & set file name                                                                                                                                                                                                                                                       
        CurrentDate=`date`                                                                                                                                                                                                                                                               
        FileNameDate=`date +%Y%m%d`                                                                                                                                                                                                                                                      
        CurrentDayLogFile="/ysdisk/support/tmp/ExtReg-LinkusLogin-$FileNameDate.csv"                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                         
        # add table header                                                                                                                                                                                                                                                               
        if [ -e $CurrentDayLogFile ];then                                                                                                                                                                                                                                                
			echo "File exists" > /dev/null                                                                                                                                                                                                                                                   
		else                                                                                                                                                                                                                                                                             
			echo "Time,ExtensoinRegistered,LinkusWebLogged,LinkusMobileLogged,LinkusPCLogged" >> $CurrentDayLogFile                                                                                                                                                                          
        fi                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                         
        # insert call current record                                                                                                                                                                                                                                                     
        echo "$CurrentDate,$REG,$WebLogged,$MobileLogged,$PcLogged" >> $CurrentDayLogFile                                                                                                                                                                        

# set print period                                                                                                                                                                                                                                                                                        
sleep 10

done      
