#!/bin/sh                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                         
# initialzed asterisk env                                                                                                                                                                                                                                                                
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ysdisk/ysapps/pbxcenter/lib/                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                         
# sleep 120                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                         
# periodic global cc                                                                                                                                                                                                                                                                
while true; do                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
        # count cc                                                                                                                                                                                                                                                                       
        CurrentCC=`asterisk -rx "core show channels" | grep "max active call" | awk -F ' ' '{print $1}'`                                                                                                                                                                                   
        echo "Current call is $CurrentCC"                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                         
        TotalCC=`asterisk -rx "core show channels" | grep "max active call" | awk -F ' ' '{print $3}'`                                                                                                                                                                                
        echo "Global call is $TotalCC"                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                  
        # get date & set file name                                                                                                                                                                                                                                                       
        CurrentDate=`date`                                                                                                                                                                                                                                                               
        FileNameDate=`date +%Y%m%d`                                                                                                                                                                                                                                                      
        CurrentDayLogFile="/ysdisk/support/tmp/GlobalCC-$FileNameDate.csv"                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                         
        # add table header                                                                                                                                                                                                                                                               
        if [ -e $CurrentDayLogFile ];then                                                                                                                                                                                                                                                
			echo "File exists" > /dev/null                                                                                                                                                                                                                                                   
		else                                                                                                                                                                                                                                                                             
			echo "Time,CurrentConcurrentCalls,TotalConcurrentCalls" >> $CurrentDayLogFile                                                                                                                                                                          
        fi                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                         
        # insert call current record                                                                                                                                                                                                                                                     
        echo "$CurrentDate,$CurrentCC,$TotalCC" >> $CurrentDayLogFile                                                                                                                                                                        

# set print period                                                                                                                                                                                                                                                                                        
sleep 10                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                         
done
